# Generated by Django 5.0.2 on 2024-03-02 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_and_assurance', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('companyemail', models.EmailField(default=django.utils.timezone.now, max_length=100, null=True)),
                ('companyname', models.CharField(default='', max_length=100)),
                ('companyphone', models.CharField(default='', max_length=100)),
                ('companysize', models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('100+', '100+')], default='', max_length=10)),
                ('financial_analysis', models.BooleanField(default=False)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('taxation', models.BooleanField(default=False)),
            ],
        ),
    ]
