# Generated by Django 5.0.2 on 2024-03-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_appointment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='companyname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='companyphone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='companysize',
            field=models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('100+', '100+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
    ]
